src/objects/BillingFrequency__c.object
<CustomObject>
    <description>Billing Frequency such as daily, weekly, monthly etc</description>
    <fields>
        <fullName>BillingFrequencyID__c</fullName>
        <description>Billing Frequency ID</description>
        <inlineHelpText>Enter billing frequency ID</inlineHelpText>
        <label>Billing Frequency ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Billing Frequency</label>
    <nameField>
        <label>Billing Frequency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Frequencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Currency__c.object
<CustomObject>
    <description>Currency Object</description>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <description>Three characters currency code such as USD, JPY etc</description>
        <inlineHelpText>Enter Currency Code</inlineHelpText>
        <label>Currency Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <description>Store information about customers</description>
    <fields>
        <fullName>CustName__c</fullName>
        <description>Customer name</description>
        <inlineHelpText>Enter customer name</inlineHelpText>
        <label>Customer Name</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>Customer orders from CRM</description>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A link to billing frequency object</description>
        <inlineHelpText>Select billing frequency</inlineHelpText>
        <label>Billing Frequency</label>
        <referenceTo>BillingFrequency__c</referenceTo>
        <relationshipLabel>Order Billing Frequency</relationshipLabel>
        <relationshipName>OrderBillingFrequency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comments</description>
        <inlineHelpText>Enter comments</inlineHelpText>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContractExists__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicate whether a contract already exists</description>
        <inlineHelpText>Must be checked for orders within existing contracts</inlineHelpText>
        <label>Contract Exists</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreditCardID__c</fullName>
        <description>Credit card ID.  A link to Credit Card Object</description>
        <inlineHelpText>Enter Credit Card ID. Note credit card number</inlineHelpText>
        <label>Credit Card ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentNet__c</fullName>
        <description>Summary on current net from Order lines</description>
        <label>Current Net</label>
        <summarizedField>OrderLine__c.CurrentNet__c</summarizedField>
        <summaryForeignKey>OrderLine__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to customer object</description>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Sum of discount from order line</description>
        <label>Discount</label>
        <summarizedField>OrderLine__c.Discount__c</summarizedField>
        <summaryForeignKey>OrderLine__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>FunctionalCurrency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Function Current</description>
        <inlineHelpText>Select functional currency</inlineHelpText>
        <label>Functional Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Functional Currency</relationshipLabel>
        <relationshipName>Currency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsEmailInvoice__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicate whether invoice is emailed</description>
        <inlineHelpText>Must be checked for invoices to be delivered electronically by email</inlineHelpText>
        <label>Email Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsNewOrder__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicate whether this is a new order</description>
        <inlineHelpText>Must be checked for new orders</inlineHelpText>
        <label>Is New Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRecurringOrder__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicate a recurring order</description>
        <inlineHelpText>Must be checked for recurring orders</inlineHelpText>
        <label>Is Recurring Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNbr__c</fullName>
        <description>Order Number in CRM</description>
        <inlineHelpText>Enter Order Number. This value is mandatory</inlineHelpText>
        <label>OrderNbr</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrderStatus__c</fullName>
        <description>Order Status, Can be active 1, Suspended 2, Declined 3 etc</description>
        <inlineHelpText>Enter Order Status</inlineHelpText>
        <label>OrderStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReportingCurrency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reporting currency</description>
        <inlineHelpText>Select reporting currency</inlineHelpText>
        <label>Reporting Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Reporting Currency</relationshipLabel>
        <relationshipName>OrderReportingCurrency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceCancelDate__c</fullName>
        <description>Service Cancel Date</description>
        <inlineHelpText>Enter service cancel date when applicable</inlineHelpText>
        <label>ServiceCancelDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceEndDate__c</fullName>
        <defaultValue>Today()+30</defaultValue>
        <description>Service End Date</description>
        <inlineHelpText>Enter Service End Date</inlineHelpText>
        <label>Service End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceStartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date when service starts</description>
        <inlineHelpText>Enter Service Start Date</inlineHelpText>
        <label>Service Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SoldByPartnerNbr__c</fullName>
        <description>Partner ID number linking to Partner object</description>
        <inlineHelpText>Enter Partner ID number</inlineHelpText>
        <label>Sold By Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderLine__c.object
<CustomObject>
    <description>Line items in an order</description>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A link to billing frequency</description>
        <inlineHelpText>Select billing frequency</inlineHelpText>
        <label>Billing Frequency</label>
        <referenceTo>BillingFrequency__c</referenceTo>
        <relationshipLabel>Order Line Billing Frequency</relationshipLabel>
        <relationshipName>OrderLinesBillingFrequency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentNet__c</fullName>
        <description>Current net amount</description>
        <inlineHelpText>Enter net amount</inlineHelpText>
        <label>Current Net</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Discount amount</description>
        <inlineHelpText>Enter discount amount</inlineHelpText>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FunctionalCurrency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Function currency</description>
        <inlineHelpText>Select functional currency</inlineHelpText>
        <label>Functional Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Order Lines Functional Currency</relationshipLabel>
        <relationshipName>OrderLinesFunctionalCurrency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobsQty__c</fullName>
        <description>Number of jobs</description>
        <inlineHelpText>Enter number of jobs</inlineHelpText>
        <label>Jobs Qty</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LineNum__c</fullName>
        <description>Order line number</description>
        <inlineHelpText>Auto generated line number</inlineHelpText>
        <label>Line Num</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Parent order object</description>
        <inlineHelpText>Select a parent record</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReportingCurrency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reporting currency</description>
        <inlineHelpText>Select reporting currency</inlineHelpText>
        <label>Reporting Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Order Lines Reporting Currency</relationshipLabel>
        <relationshipName>OrderLinesReportingCurrency</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceEndDate__c</fullName>
        <defaultValue>Today() + 30</defaultValue>
        <description>Service end date</description>
        <inlineHelpText>Enter service end date</inlineHelpText>
        <label>Service End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OLN-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderResource.cls
@RestResource(urlMapping='/Order/*')
global with sharing class OrderResource {

class OrderLineUpd
    {
        public string Id { get; set; }
        public double CurrentNet { get; set; }
        public double Discount { get; set; }
        public integer JobsQty { get; set; }
        public integer UsersQty { get; set; }
    }

  @HttpDelete
  global static void doDelete() {
     RestRequest req = RestContext.request;
     RestResponse res = RestContext.response;
     String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
     Account account = [SELECT Id FROM Account WHERE Id = :accountId];
     delete account;
  }
  @HttpGet
  global static LIST<Order__C> doGet() {
     RestRequest req = RestContext.request;
     RestResponse res = RestContext.response;
     String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
     LIST<Order__C> result = [SELECT BillingFrequency__r.BillingFrequencyID__c, BillingFrequency__r.Name, comment__c, ContractExists__c, CreditCardID__c,CurrentNet__c, Customer__r.CustName__c, Discount__c, IsEmailInvoice__c,            
                                     FunctionalCurrency__r.Name, FunctionalCurrency__r.CurrencyCode__c, IsNewOrder__c, IsRecurringOrder__c, OrderNbr__c, OrderStatus__c, ReportingCurrency__r.Name, ReportingCurrency__r.CurrencyCode__c,   
                                    ServiceCancelDate__c, ServiceEndDate__c, ServiceStartDate__c, SoldByPartnerNbr__c, 
                                   (SELECT BillingFrequency__r.BillingFrequencyID__c, BillingFrequency__r.Name, CurrentNet__c, Discount__c, FunctionalCurrency__r.Name, FunctionalCurrency__r.CurrencyCode__c, 
                       JobsQty__c, LineNum__c, Market__c, ReportingCurrency__r.Name, ReportingCurrency__r.CurrencyCode__c, ServiceEndDate__c, ServiceStart__c, Status__c, ThirtyDayUpg__c, 
                       UsersQty__c, WebsiteName__c, WebstoreUpg__c 
                    FROM Order_Lines__r)
                              FROM Order__c];
   return result;
  }
  @HttpPost
   global static String doPost() {
     RestRequest req = RestContext.request;
     RestResponse res = RestContext.response;
     string jsonBody = req.requestBody.toString();
     OrderLineUpd orderLineUpd  = (OrderLineUpd)JSON.deserialize(jsonBody, OrderResource.OrderLineUpd.class);
     OrderLine__c orderLine = [SELECT CurrentNet__c, Discount__c, JobsQty__c, UsersQty__c FROM OrderLine__c WHERE Id = :orderLineUpd.Id];
     orderLine.CurrentNet__c = orderLineUpd.CurrentNet;
     orderLine.Discount__c = orderLineUpd.Discount;
     orderLine.JobsQty__c = orderLineUpd.JobsQty;
     orderLine.UsersQty__c = orderLineUpd.UsersQty;
     update orderLine;

   return orderLineUpd.Id;
  }
}